"""Initial migration

Revision ID: ab77a4968437
Revises: 
Create Date: 2026-04-21 11:04:08.966386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab77a4968437'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'instruction',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'timeout_seconds')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'dispatched_at')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.VARCHAR(length=500), nullable=False))
    op.add_column('tasks', sa.Column('dispatched_at', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('timeout_seconds', sa.INTEGER(), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.VARCHAR(length=20), nullable=False))
    op.alter_column('tasks', 'instruction',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
